apiVersion: v1
data:
  meow.yaml: |+
    input:
      generate:
        mapping: root = "meow" # Generates a message with the word "meow" at regular intervals.
        interval: 2s
        count: 0
    output:
      stdout:
        codec: lines # Outputs each message as a new line in stdout.

  woof.yaml: |
    input:
      generate:
        mapping: root = "woof" # Generates a message with the word "woof" at regular intervals.
        interval: 5s
        count: 0
    output:
      stdout:
        codec: lines # Outputs each message as a new line in stdout.
kind: ConfigMap
metadata:
  name: connect-streams
  namespace: redpanda-connect
