apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redpanda-connect
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}


# 1) Generate the ConfigMap WITH hash in the name
configMapGenerator:
  - name: connect-streams
    files:
      - config/woof.yaml
      - config/meow.yaml
generatorOptions:
  disableNameSuffixHash: false

# 2) Inflate the Redpanda Connect Helm chart
helmCharts:
  - name: connect
    repo: https://charts.redpanda.com
    version: 3.1.0
    releaseName: redpanda-connect-streams
    namespace: redpanda-connect
    includeCRDs: true
    #valuesFile:
    valuesInline:
      streams:
        enabled: true
        streamsConfigMap: connect-streams
      deployment:
        replicaCount: 3
