input:
  label: "generate-woof"
  generate:
    mapping: root = "woof" # Generates a message with the word "woof" at regular intervals.
    interval: 5s
    count: 0
output:
  label: "output-woof"
  stdout:
    codec: lines # Outputs each message as a new line in stdout.
